### PR TITLE
Ci 02

### PR DESCRIPTION
**Pull request by andrewbird**
Have a look and see what you think about using Github Pages to host the latest successful build from master.
https://andrewbird.github.io/comcom32/

I think it will do what you want, but don't merge this until I've cleaned up the my gh-pages branch (which needs merging first).

### CODE REVIEW

**Comment by stsp** [comment]
> Have a look and see what you think about using Github Pages to host the latest successful build from master.

Looks cool, just a zipped exe and a stable link!
Thanks.

**Comment by andrewbird** [comment]
So can you checkout my https://github.com/andrewbird/comcom32/tree/gh-pages branch and push it to dosemu2/comcom32/gh-pages, please? You'll then need to setup Github Pages for the repository using your new gh-pages branch as the base, and you can pick any theme (I used minimal). Once done, you can test it's active via this link https://dosemu2.github.io/comcom32/files/README.md

**Comment by stsp** [comment]
Thanks.

**Comment by stsp** [comment]
> So can you checkout my https://github.com/andrewbird/comcom32/tree/gh-pages
> branch and push it to dosemu2/comcom32/gh-pages, please?

Why do I need that?
Is it needed for a stable link to work?

**Comment by stsp** [comment]
Btw, its perfectly fine to not have
a visible link and README at all.
I just need the link to work, but it
doesn't have to be visible anywhere.
So why do you say it should replace
any normal gh-pages?

**Comment by andrewbird** [comment]
> I just need the link to work, but it
doesn't have to be visible anywhere.

Yes that's the way I had it earlier, but I wanted to show the link in case anyone forgot what the path was.

> So why do you say it should replace
any normal gh-pages?

That's what it does by default, it removes what's there already and then adds the files specified. For that reason the README.md is no more, see https://github.com/dosemu2/comcom32/tree/gh-pages. I've since discovered there is a `keep_files` option, but I haven't tested it.

**Comment by stsp** [comment]
> but I wanted to show the link in case anyone forgot what the path was.

This is just for me to hard-code
the URL into the buildroot script.
No one would look or use it otherwise.
So if such URL already exists - what
is it?

**Comment by andrewbird** [comment]
> So if such URL already exists - what
is it?

Not that I know of.

You can remove this line if it bothers you
https://github.com/dosemu2/comcom32/blob/ca280ee01102a2e2ede9f23bb5dda362dfdb435a/.github/workflows/ci-build.yml#L35

**Comment by stsp** [comment]
All I need is an URL.
I don't care if its visible or not.
So where is it?

**Comment by andrewbird** [comment]
It should be here https://dosemu2.github.io/comcom32/files/comcom32.zip, but isn't. Did you create the github pages for comcom32 as I asked here https://github.com/dosemu2/comcom32/pull/52#issuecomment-816652192 ?

**Comment by andrewbird** [comment]
If you did, then it was probably after you merged my ci-02 branch because I can see from its ci run it was missing.
~~~
Cloning into '/home/runner/actions_github_pages_1617974167092'...
  warning: Could not find remote branch gh-pages to clone.
  fatal: Remote branch gh-pages not found in upstream origin
  [INFO] first deployment, create new branch gh-pages
  [INFO] The process '/usr/bin/git' failed with exit code 128
~~~

**Comment by stsp** [comment]
I didn't because I thought
its just to make the URL visible
on gh-pages, so not really needed.
And you erased it anyway.
Would it be possible to provide it
via a PR?

**Comment by andrewbird** [comment]
> Would it be possible to provide it
via a PR?

I've put the branch back. I can't do PR because it's an orphan as we don't want code in there. You should be able to do something like
~~~
git checkout andrewbird/gh-pages
git push origin gh-pages
~~~

Or make your own orphan branch
~~~
git checkout --orphan gh-pages
git reset --hard
git status
# remove all the files and directories
mkdir files
touch files/README.md
git add files/README.md
git commit -a -m "Initial commit"
git push origin gh-pages
~~~

BTW I'm painting the house today, hence the latency in my responses!

**Comment by stsp** [comment]
Thanks, seems to work.
So does the file appear only after
you make the URL visible via pages?
Because your commit only contains
dummy README.md, so I don't understand
how does it help.

**Comment by andrewbird** [comment]
> So does the file appear only after
you make the URL visible via pages?

It's just that the build Action writes to the branch which is configured in Pages. Pages has to be enabled for the URL to be active. I created the dummy README.md only to ensure that the 'files' directory would exist as git doesn't store empty directories.

**Comment by stsp** [comment]
OK, thanks for explanation.
I updated our buildroot.

**Pull request merged**
