### PR TITLE
Travis: Initial integration

### PR DESCRIPTION
**Pull request by andrewbird**
Here's the build of comcom32 package and the installation of it, dosemu2 & fdpp. You'll just need to configure Travis to see the repo and add test now.

### CODE REVIEW

**Comment by stsp** [comment]
Thanks!

**Comment by stsp** [comment]
In travis I already have:
```
All repositories
This applies to all current and future repositories. 
```

So I guess that part should work.

**Comment by andrewbird** [comment]
Yes it's working, thanks.

**Comment by stsp** [comment]
So someone needs to write the
ae00/ae01 support, and we are good
on features.

**Comment by andrewbird** [comment]
And obviously there are no tests as such at the moment, only build + install + dosemu boot to display comcom32 version.

**Pull request merged**
